# Generated by Django 5.1.6 on 2025-02-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotation_requests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotationrequests",
            name="review_count",
            field=models.IntegerField(default=0),
        ),
    ]
