# Generated by Django 5.1.6 on 2025-02-12 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quotation_requests", "0002_alter_quotationrequests_review_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quotationrequests",
            old_name="responded_at",
            new_name="responded_on",
        ),
    ]
