# Generated by Django 5.1.6 on 2025-02-13 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "quotation_requests",
            "0003_rename_responded_at_quotationrequests_responded_on",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotationrequests",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
        ),
        migrations.AlterField(
            model_name="quotationrequests",
            name="customer",
            field=models.CharField(max_length=100, verbose_name="Cliente"),
        ),
        migrations.AlterField(
            model_name="quotationrequests",
            name="deadline",
            field=models.DateTimeField(verbose_name="Deadline"),
        ),
        migrations.AlterField(
            model_name="quotationrequests",
            name="difal_check",
            field=models.BooleanField(default=False, verbose_name="DIFAL?"),
        ),
        migrations.AlterField(
            model_name="quotationrequests",
            name="quotation_total_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name="Valor Orçado",
            ),
        ),
        migrations.AlterField(
            model_name="quotationrequests",
            name="responded_on",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Orçado em"),
        ),
        migrations.AlterField(
            model_name="quotationrequests",
            name="review_count",
            field=models.IntegerField(default=0, verbose_name="Revisão da Solicitação"),
        ),
        migrations.AlterField(
            model_name="quotationrequests",
            name="sale_state",
            field=models.CharField(
                choices=[
                    ("AC", "Acre"),
                    ("AL", "Alagoas"),
                    ("AP", "Amapá"),
                    ("AM", "Amazonas"),
                    ("BA", "Bahia"),
                    ("CE", "Ceará"),
                    ("DF", "Distrito Federal"),
                    ("ES", "Espírito Santo"),
                    ("GO", "Goiás"),
                    ("MA", "Maranhão"),
                    ("MT", "Mato Grosso"),
                    ("MS", "Mato Grosso do Sul"),
                    ("MG", "Minas Gerais"),
                    ("PA", "Pará"),
                    ("PB", "Paraíba"),
                    ("PR", "Paraná"),
                    ("PE", "Pernambuco"),
                    ("PI", "Piauí"),
                    ("RJ", "Rio de Janeiro"),
                    ("RN", "Rio Grande do Norte"),
                    ("RS", "Rio Grande do Sul"),
                    ("RO", "Rondônia"),
                    ("RR", "Roraima"),
                    ("SC", "Santa Catarina"),
                    ("SP", "São Paulo"),
                    ("SE", "Sergipe"),
                    ("TO", "Tocantins"),
                ],
                max_length=2,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="quotationrequests",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Título do Projeto"),
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("TA", "Tanque Armazenagem"),
                            ("TTE", "Tanque Tratamento de Efluentes"),
                            ("VP", "Vaso de Pressão"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Equipamento",
                    ),
                ),
                (
                    "equipment_model",
                    models.CharField(
                        choices=[
                            ("FPTE", "Fundo Plano/Tampo Elíptico"),
                            ("FPTP", "Fundo Plano/Tampo Plano"),
                            ("TH", "Tanque Horizontal"),
                        ],
                        max_length=30,
                        verbose_name="Modelo de Equipamento",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "quotation_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipments",
                        to="quotation_requests.quotationrequests",
                    ),
                ),
            ],
        ),
    ]
