# Generated by Django 5.1.6 on 2025-02-13 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotation_requests", "0004_alter_quotationrequests_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="quotation_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="quotation_requests.quotationrequests",
            ),
        ),
    ]
