# Generated by Django 5.1.6 on 2025-02-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotation_requests", "0006_equipment_temp_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotationrequests",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
