# Generated by Django 5.1.6 on 2025-02-13 20:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotation_requests", "0007_alter_quotationrequests_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="composed_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="quotation_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quotation_requests.quotationrequests",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="temp_id",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
    ]
